const types = {
  // LEAGUES
  GET_LEAGUES_START: "GET_LEAGUES_START",
  GET_LEAGUES_SUCCESS: "GET_LEAGUES_SUCCESS",
  GET_LEAGUES_ERROR: "GET_LEAGUES_ERROR",

  // TEAMS
  GET_TEAMS_START: "GET_TEAMS_START",
  GET_TEAMS_SUCCESS: "GET_TEAMS_SUCCESS",
  GET_TEAMS_ERROR: "GET_TEAMS_ERROR",

  // GAMES
  GET_GAMES_START: "GET_GAMES_START",
  GET_GAMES_SUCCESS: "GET_GAMES_SUCCESS",
  GET_GAMES_ERROR: "GET_GAMES_ERROR",

  // CURRENT GAME
  GET_CURRENT_GAME: "GET_CURRENT_GAME",
};

export default types;
